# SPDX-FileCopyrightText: 2024 The HC Authors
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

version = 1

[[annotations]]
path = [
    "llvm-sha.txt",
    "tests/Dialect/**",
    "tests/pyfront/**",
    "tests/Transforms/**"
]
SPDX-FileCopyrightText = "2024 The HC Authors"
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"
